# Makefile for writing Make Files Example
# **************************************************
# Variables to control Makefile operation
CC = g++
CFLAGS = -Wall -g
# *************************************************

foo: foo.o
	$(CC) charpter_01.cpp foo.o -o charpter_01 
